language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9.2  # macOS-10.12
      compiler: clang
    - os: osx
      osx_image: xcode9.4  # macOS-10.13
      compiler: clang
    - os: osx
      osx_image: xcode10
      compiler: clang

script:
  - brew tap dreal-deps/ibex
  - brew update
  - brew install dreal-deps/ibex/ibex@2.7.2 --only-dependencies || true
  - brew install dreal-deps/ibex/ibex@2.7.2 --build-from-source
  - brew test ibex@2.7.2

notifications:
  email:
    recipients:
     - soonho.kong@gmail.com
