language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      compiler: clang
    - os: osx
      osx_image: xcode9
      compiler: clang

script:
  - rm /usr/local/include/c++ # https://github.com/Homebrew/brew/issues/1742#issuecomment-277308817
  - brew update
  - brew install dreal-deps/ibex/ibex@2.6.5 --only-dependencies || true
  - brew install dreal-deps/ibex/ibex@2.6.5 --build-from-source

notifications:
  email:
    recipients:
     - soonho.kong@gmail.com
