language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      compiler: clang
    - os: osx
      osx_image: xcode9
      compiler: clang

install:
  - brew install dreal-deps/ibex/ibex

notifications:
  email:
    recipients:
     - soonho.kong@gmail.com
